"use client";

import { FormEvent, useState } from "react";
import { Plus, UserRound } from "lucide-react";
import { EmptyStateCard, RiskBadge, PageIntro, Panel } from "@/components/enterprise/EnterpriseUI";
import EnterpriseDialog from "@/components/enterprise/EnterpriseDialog";
import { useEnterpriseStore } from "@/store/enterprise-store";
import type { RiskLevel } from "@/types/enterprise";

const stages = ["待处理","处理中","待复核","已完成"] as const;
export default function WorkflowsPage() {
  const tasks = useEnterpriseStore((state) => state.tasks); const addTask = useEnterpriseStore((state) => state.addTask); const advanceTask = useEnterpriseStore((state) => state.advanceTask); const [open,setOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); addTask({ title:String(data.get("title")), caseName:String(data.get("caseName")), assignee:String(data.get("assignee")), due:String(data.get("due")), priority:String(data.get("priority")) as RiskLevel }); setOpen(false); };
  return <div className="page-shell"><PageIntro eyebrow="Human-in-the-loop" title="研判流程中心" description="将 Agent 发现转化为明确的补充资料、核验、复核与审批任务，让人机协作真正进入业务流程。" actions={<button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-[#041018]"><Plus className="h-3.5 w-3.5" />创建任务</button>} />
    {tasks.length === 0 ? <Panel><EmptyStateCard title="还没有人工任务" description="将资料补充、证据核验、规则复核或审批动作登记为任务，让 AI 研判结果进入可追踪的人工流程。" action={<button onClick={() => setOpen(true)} className="rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-[#041018]">创建首个任务</button>} /></Panel> : <div className="grid gap-4 xl:grid-cols-4">{stages.map(stage => <section key={stage} className="rounded-2xl border border-white/[0.08] bg-white/[0.018] p-3"><div className="mb-3 flex items-center justify-between px-1"><h2 className="text-xs font-semibold text-slate-300">{stage}</h2><span className="grid h-5 min-w-5 place-items-center rounded-md bg-white/[0.06] px-1 text-[10px] text-slate-500">{tasks.filter(task=>task.stage===stage).length}</span></div><div className="space-y-3">{tasks.filter(task=>task.stage===stage).map(task => <article key={task.id} className="rounded-xl border border-white/[0.08] bg-[#0a121e] p-3.5 shadow-lg"><div className="flex items-center justify-between"><RiskBadge level={task.priority} /><span className="text-[9px] text-slate-600">{task.id}</span></div><h3 className="mt-3 text-xs font-medium leading-5 text-slate-200">{task.title}</h3><p className="mt-1.5 text-[10px] text-cyan-300/60">{task.caseName}</p><div className="mt-4 flex items-center justify-between border-t border-white/[0.06] pt-3"><span className="flex items-center gap-1.5 text-[10px] text-slate-500"><UserRound className="h-3 w-3" />{task.assignee}</span><span className={`text-[10px] ${task.due.includes("超期") ? "text-rose-300" : "text-slate-600"}`}>{task.due}</span></div>{stage!=="已完成" && <button onClick={()=>advanceTask(task.id)} className="mt-3 w-full rounded-lg border border-white/[0.08] py-2 text-[10px] text-slate-400 hover:border-cyan-400/20 hover:text-cyan-300">推进至下一阶段</button>}</article>)}</div></section>)}</div>}
    <EnterpriseDialog open={open} onClose={() => setOpen(false)} title="创建人工研判任务"><form onSubmit={submit} className="space-y-4">{[["title","任务内容","填写需要人工处理或复核的事项"],["caseName","关联项目","填写关联的企业项目"],["assignee","负责人","填写任务负责人"],["due","截止时间","填写明确的截止时间"]].map(([name,label,placeholder]) => <label key={name} className="block"><span className="mb-1.5 block text-[11px] text-slate-400">{label}</span><input required name={name} placeholder={placeholder} className="field-control" /></label>)}<label className="block"><span className="mb-1.5 block text-[11px] text-slate-400">优先级</span><select name="priority" className="field-control"><option value="medium">中风险</option><option value="high">高风险</option><option value="critical">重大风险</option><option value="low">低风险</option></select></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs text-slate-400">取消</button><button type="submit" className="rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-[#041018]">创建任务</button></div></form></EnterpriseDialog>
  </div>;
}
