"use client";

import { ChangeEvent, useRef, useState } from "react";
import { CheckCircle2, ChevronRight, FileSpreadsheet, FileText, ScanSearch, Upload } from "lucide-react";
import { PageIntro, Panel } from "@/components/enterprise/EnterpriseUI";
import { useEnterpriseStore } from "@/store/enterprise-store";

const extractedFacts = [
  { label: "营业收入", value: "¥8.42 亿", source: "P.12 合并利润表", confidence: 98 },
  { label: "经营活动现金净额", value: "-¥3,860 万", source: "P.15 现金流量表", confidence: 97 },
  { label: "关联方其他应收款", value: "¥7,420 万", source: "P.86 关联方披露", confidence: 94 },
  { label: "对外担保余额", value: "¥1.90 亿", source: "P.103 或有事项", confidence: 92 },
];

export default function DocumentsPage() {
  const documents = useEnterpriseStore((state) => state.documents);
  const addDocument = useEnterpriseStore((state) => state.addDocument);
  const [selected, setSelected] = useState(documents[0]); const [tab, setTab] = useState("事实抽取");
  const [notice, setNotice] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const item = addDocument(file); setSelected(item); setNotice(`${file.name} 已加入研判队列`); event.target.value = ""; };
  return <div className="page-shell"><PageIntro eyebrow="Document intelligence" title="企业资料研判工作台" description="将审计报告、合同、流水与访谈纪要转化为可引用事实，并逐条匹配业务规则与风险证据。" actions={<><input ref={fileRef} type="file" accept=".pdf,.docx,.xlsx,.csv,.txt" onChange={upload} className="hidden" /><button onClick={() => fileRef.current?.click()} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-[#041018]"><Upload className="h-3.5 w-3.5" />上传资料</button></>} />
    {notice && <button onClick={() => setNotice("")} className="w-full rounded-xl border border-emerald-400/15 bg-emerald-400/[0.05] px-4 py-3 text-left text-xs text-emerald-300">{notice} · 点击关闭</button>}
    <div className="grid min-h-[620px] gap-4 xl:grid-cols-[.78fr_1.45fr_1fr]">
      <Panel className="flex min-h-0 flex-col"><div className="border-b border-white/[0.07] p-4"><p className="text-xs font-semibold text-slate-200">项目资料</p><p className="mt-1 text-[10px] text-slate-600">{documents.length} 份资料 · {documents.reduce((sum, doc) => sum + doc.facts, 0)} 个事实 · {documents.reduce((sum, doc) => sum + doc.ruleHits, 0)} 项规则命中</p></div><div className="scrollbar-thin min-h-0 flex-1 overflow-y-auto p-2">{documents.map(doc => { const Icon = doc.kind === "经营数据" ? FileSpreadsheet : FileText; return <button key={doc.id} onClick={() => setSelected(doc)} className={`mb-1 w-full rounded-xl border p-3 text-left transition ${selected.id === doc.id ? "border-cyan-400/20 bg-cyan-400/[0.07]" : "border-transparent hover:bg-white/[0.035]"}`}><div className="flex gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-white/[0.07] bg-white/[0.04]"><Icon className="h-4 w-4 text-cyan-300" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-slate-200">{doc.name}</p><p className="mt-1 text-[10px] text-slate-600">{doc.kind} · {doc.pages} 页</p><div className="mt-2 flex items-center justify-between"><span className={doc.status === "解析中" ? "text-[10px] text-amber-300" : "text-[10px] text-emerald-300"}>{doc.status}</span><span className="numeric text-[10px] text-slate-600">置信度 {doc.confidence}%</span></div></div></div></button>})}</div></Panel>
      <Panel className="flex min-h-0 flex-col"><div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-3"><div><p className="max-w-md truncate text-xs font-medium text-slate-200">{selected.name}</p><p className="mt-1 text-[10px] text-slate-600">原文预览 · 第 86 / {selected.pages} 页</p></div><button onClick={() => setNotice(`已定位 ${selected.name} 的原文证据页`)} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] text-slate-400">定位原文件</button></div><div className="relative flex-1 overflow-hidden bg-[#0d131c] p-4 sm:p-8"><div className="mx-auto min-h-[510px] max-w-lg rounded-sm bg-[#f4f1e9] p-8 text-[#28303a] shadow-2xl"><p className="text-center text-[10px] tracking-[.2em] text-slate-500">晟远新能源集团股份有限公司</p><h3 className="mt-4 text-center text-lg font-bold">财务报表附注</h3><p className="mt-8 text-xs font-semibold">十二、关联方及关联交易</p><p className="mt-4 text-[11px] leading-6">截至报告期末，公司应收关联方款项余额合计为人民币 74,203,500.00 元，较上年末增长 67.2%。其中，其他应收款主要为非经营性资金往来。</p><div className="relative mt-4 rounded border-2 border-cyan-500/80 bg-cyan-100/35 p-3 text-[11px] leading-6"><span className="absolute -right-2 -top-2 rounded bg-cyan-600 px-1.5 py-0.5 text-[8px] text-white">证据 E-0184</span>上述款项尚未制定明确回收计划，管理层预计于未来十二个月内通过经营回款及资产处置方式逐步收回。</div><p className="mt-5 text-[11px] leading-6">本期公司为关联企业提供的担保余额为人民币 190,000,000.00 元，详见附注十三、或有事项。</p></div></div></Panel>
      <Panel className="flex min-h-0 flex-col"><div className="flex border-b border-white/[0.07] px-2 pt-2">{["事实抽取","规则命中","引用证据"].map(name => <button key={name} onClick={() => setTab(name)} className={`flex-1 border-b-2 px-2 py-3 text-[11px] ${tab === name ? "border-cyan-300 text-cyan-200" : "border-transparent text-slate-600"}`}>{name}</button>)}</div><div className="scrollbar-thin flex-1 overflow-y-auto p-4">{tab === "事实抽取" && <div className="space-y-3">{extractedFacts.map(fact => <div key={fact.label} className="rounded-xl border border-white/[0.07] bg-white/[0.022] p-3.5"><div className="flex justify-between"><p className="text-[11px] text-slate-500">{fact.label}</p><span className="text-[9px] text-emerald-300">{fact.confidence}%</span></div><p className="numeric mt-2 text-sm font-semibold text-white">{fact.value}</p><button className="mt-2 flex items-center gap-1 text-[10px] text-cyan-300/70"><ScanSearch className="h-3 w-3" />{fact.source}<ChevronRight className="h-3 w-3" /></button></div>)}</div>}{tab === "规则命中" && <div className="space-y-3">{[["CR-08","关联方资金占用超过净资产 5%","高风险"],["CR-21","经营现金流连续两期为负","高风险"],["GR-05","新增非合并范围互保主体","中风险"]].map(([code,text,level]) => <div key={code} className="rounded-xl border border-amber-400/15 bg-amber-400/[0.035] p-3.5"><span className="text-[9px] text-amber-300">{code} · {level}</span><p className="mt-2 text-xs leading-5 text-slate-300">{text}</p><p className="mt-2 text-[10px] text-slate-600">已定位 2 条支持证据</p></div>)}</div>}{tab === "引用证据" && <div className="space-y-3">{["E-0184 · 关联方往来余额及增幅","E-0187 · 管理层预计回收安排","E-0203 · 对外担保余额"].map(item => <div key={item} className="flex items-center gap-2 rounded-xl border border-white/[0.07] p-3 text-xs text-slate-300"><CheckCircle2 className="h-4 w-4 text-emerald-400" />{item}</div>)}</div>}</div></Panel>
    </div>
  </div>;
}
