"use client";

import { useEffect, useState } from "react";
import { Bot, Braces, CheckCircle2, Clock3, GitBranch, Play, ShieldCheck } from "lucide-react";
import { PageIntro, Panel, PanelHeader } from "@/components/enterprise/EnterpriseUI";
import { useEnterpriseStore } from "@/store/enterprise-store";

export default function AgentsPage() {
  const agents = useEnterpriseStore((state) => state.agents);
  const startAgentRun = useEnterpriseStore((state) => state.startAgentRun);
  const completeAgentRun = useEnterpriseStore((state) => state.completeAgentRun);
  const [running, setRunning] = useState(false);
  useEffect(() => { if (!running) return; const timer = window.setTimeout(() => { completeAgentRun(); setRunning(false); }, 1800); return () => window.clearTimeout(timer); }, [running, completeAgentRun]);
  const run = () => { startAgentRun(); setRunning(true); };
  return <div className="page-shell"><PageIntro eyebrow="Agent orchestration" title="企业金融 Agent 中心" description="Agent 按资料理解、规则匹配、风险研判、投研整理和流程辅助分工协作；工具调用、输入与输出全程留痕。" actions={<button onClick={run} disabled={running} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-[#041018] disabled:opacity-60"><Play className="h-3.5 w-3.5" />{running ? "研判运行中…" : "运行研判链路"}</button>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{agents.map(agent => <Panel key={agent.id} className="p-4"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl border border-cyan-400/15 bg-cyan-400/[0.07]"><Bot className="h-5 w-5 text-cyan-300" /></div><span className={`rounded-md border px-2 py-1 text-[10px] ${agent.status === "已完成" ? "border-emerald-400/20 bg-emerald-400/[0.06] text-emerald-300" : agent.status === "运行中" ? "border-cyan-400/20 bg-cyan-400/[0.06] text-cyan-300" : "border-amber-400/20 bg-amber-400/[0.06] text-amber-300"}`}>{agent.status}</span></div><h2 className="mt-4 text-sm font-semibold text-slate-100">{agent.name}</h2><p className="mt-1 text-[11px] text-slate-500">{agent.role}</p><div className="mt-4 border-t border-white/[0.06] pt-3"><p className="line-clamp-2 min-h-10 text-xs leading-5 text-slate-300">{agent.task}</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full rounded-full bg-cyan-300" style={{width:`${agent.progress}%`}} /></div><div className="mt-2 flex justify-between text-[10px] text-slate-600"><span>{agent.progress}%</span><span>{agent.duration}</span></div></div></Panel>)}</div>
    <div className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Panel><PanelHeader eyebrow="Execution trace" title="当前运行轨迹" description="晟远新能源授信研判 · RUN-0826-1042" /><div className="p-5">{[["资料理解 Agent","已抽取 184 个经营与财务事实","done"],["规则匹配 Agent","命中 7 项规则，2 项需要升级核验","done"],["风险研判 Agent","正在交叉验证关联方占款与现金流","running"],["报告生成 Agent","等待上游研判结果","wait"]].map(([name,text,status],index) => <div key={name} className="relative flex gap-4 pb-6 last:pb-0"><div className="relative z-10 grid h-8 w-8 shrink-0 place-items-center rounded-full border border-white/10 bg-[#0b1420]">{status === "done" ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : status === "running" ? <Clock3 className="h-4 w-4 text-cyan-300" /> : <span className="text-[10px] text-slate-600">{index+1}</span>}</div>{index < 3 && <div className="absolute left-4 top-8 h-[calc(100%-2rem)] w-px bg-white/[0.08]" />}<div className="pt-1"><p className="text-xs font-medium text-slate-200">{name}</p><p className="mt-1 text-[11px] text-slate-500">{text}</p></div></div>)}</div></Panel><Panel><PanelHeader eyebrow="Governance" title="安全与治理" /><div className="space-y-3 p-4">{[[ShieldCheck,"人工复核闸门","重大风险结论不可自动发布"],[Braces,"工具权限最小化","按 Agent 与项目授权数据范围"],[GitBranch,"完整版本追踪","规则、提示词与输出均可回溯"]].map(([Icon,title,text]) => { const I = Icon as typeof ShieldCheck; return <div key={String(title)} className="rounded-xl border border-white/[0.07] p-3.5"><I className="h-4 w-4 text-cyan-300" /><p className="mt-2 text-xs font-medium text-slate-200">{String(title)}</p><p className="mt-1 text-[10px] leading-5 text-slate-600">{String(text)}</p></div>})}</div></Panel></div>
  </div>;
}
