"use client";

import Link from "next/link";
import { ArrowRight, Bot, CheckCircle2, CircleAlert, Clock3, FileSearch, Network, Sparkles } from "lucide-react";
import { MetricCard, PageIntro, Panel, PanelHeader, RiskBadge, riskMeta } from "@/components/enterprise/EnterpriseUI";
import { useEnterpriseStore } from "@/store/enterprise-store";

export default function EnterpriseCommandCenter() {
  const enterpriseCases = useEnterpriseStore((state) => state.cases);
  const riskSignals = useEnterpriseStore((state) => state.risks);
  const agentRuns = useEnterpriseStore((state) => state.agents);
  const documents = useEnterpriseStore((state) => state.documents);
  const resetWorkspace = useEnterpriseStore((state) => state.resetWorkspace);
  return <div className="page-shell">
    <PageIntro eyebrow="Enterprise intelligence workspace" title="企业经营与风险决策台" description="把企业资料、经营数据、制度规则与外部研究组织成可追溯的研判证据链，让 Agent 辅助判断，让关键结论始终由人复核。" actions={<><button onClick={resetWorkspace} className="hidden rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-500 hover:text-white sm:inline-flex">重置演示数据</button><Link href="/assistant" className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-semibold text-[#041018]"><Sparkles className="h-3.5 w-3.5" />开始智能研判</Link></>} />

    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard label="进行中项目" value={String(enterpriseCases.filter(item => item.status !== "已完成").length)} detail="实时更新" trend="up" /><MetricCard label="待复核资料" value={String(documents.filter(item => item.status !== "已解析").length)} detail={`${documents.length} 份总资料`} trend="down" accent="amber" /><MetricCard label="高风险信号" value={String(riskSignals.filter(item => item.level === "critical" || item.level === "high").length)} detail={`${riskSignals.filter(item => item.status === "待核验").length} 项待核验`} trend="up" accent="rose" /><MetricCard label="平均研判周期" value="2.4 天" detail="效率 +18%" trend="down" accent="emerald" /></div>

    <Panel className="relative bg-gradient-to-r from-[#0b1825] to-[#08111c]">
      <div className="absolute right-0 top-0 h-64 w-64 rounded-full bg-cyan-400/[0.05] blur-3xl" />
      <div className="relative grid gap-6 p-5 lg:grid-cols-[1.3fr_.7fr] lg:p-6"><div><div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[.18em] text-cyan-300/70"><Bot className="h-4 w-4" />FinOS Intelligence</div><h2 className="mt-3 text-xl font-semibold tracking-tight text-white">今天需要优先处理什么？</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">科泽生物并购融资出现重大或有负债信号；晟远新能源关联方占款已触发两项授信规则。建议先完成证据核验，再推进审批。</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/risk" className="inline-flex items-center gap-2 rounded-lg border border-rose-400/20 bg-rose-400/[0.08] px-3 py-2 text-xs text-rose-200"><CircleAlert className="h-3.5 w-3.5" />查看 3 项高风险</Link><Link href="/documents" className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2 text-xs text-slate-300"><FileSearch className="h-3.5 w-3.5" />复核证据材料</Link></div></div><div className="rounded-xl border border-white/[0.07] bg-black/15 p-4"><p className="text-xs font-medium text-slate-300">研判链路完整度</p><div className="mt-4 space-y-3">{[["资料解析", "92%", "bg-cyan-300"],["规则覆盖", "84%", "bg-blue-400"],["人工复核", "61%", "bg-amber-300"]].map(([name,value,color]) => <div key={name}><div className="mb-1.5 flex justify-between text-[11px]"><span className="text-slate-500">{name}</span><span className="numeric text-slate-300">{value}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><div className={`h-full rounded-full ${color}`} style={{ width: value }} /></div></div>)}</div></div></div>
    </Panel>

    <div className="grid gap-4 xl:grid-cols-[1.6fr_1fr]">
      <Panel><PanelHeader eyebrow="Case queue" title="重点项目队列" description="按照风险、时效与资料完整度综合排序" action={<Link href="/cases" className="flex items-center gap-1 text-xs text-cyan-300">全部项目<ArrowRight className="h-3 w-3" /></Link>} /><div className="divide-y divide-white/[0.06]">{enterpriseCases.slice(0,3).map(item => <Link href="/cases" key={item.id} className="grid gap-3 px-5 py-4 transition hover:bg-white/[0.025] sm:grid-cols-[1.4fr_.65fr_.6fr] sm:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-medium text-slate-100">{item.company}</p><RiskBadge level={item.risk} /></div><p className="mt-1.5 truncate text-xs text-slate-500">{item.title} · {item.id}</p></div><div><p className="numeric text-sm text-slate-200">{item.amount}</p><p className="mt-1 text-[11px] text-slate-600">负责人 {item.owner}</p></div><div><div className="flex justify-between text-[10px] text-slate-500"><span>{item.status}</span><span>{item.progress}%</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${item.progress}%` }} /></div></div></Link>)}</div></Panel>
      <Panel><PanelHeader eyebrow="Risk radar" title="最新风险信号" description="可回溯至原文证据与命中规则" /><div className="divide-y divide-white/[0.06]">{riskSignals.slice(0,3).map(signal => <Link href="/risk" key={signal.id} className="block px-5 py-4 hover:bg-white/[0.025]"><div className="flex items-center gap-2"><span className={`h-1.5 w-1.5 rounded-full ${riskMeta[signal.level].dot}`} /><p className="truncate text-xs font-medium text-slate-200">{signal.title}</p></div><p className="mt-2 line-clamp-2 text-[11px] leading-5 text-slate-500">{signal.evidence}</p><p className="mt-2 text-[10px] text-slate-600">{signal.company} · {signal.rule}</p></Link>)}</div></Panel>
    </div>

    <div className="grid gap-4 lg:grid-cols-2">
      <Panel><PanelHeader eyebrow="Agent operations" title="Agent 实时协作" description="每一步均保留输入、工具与输出记录" action={<Link href="/agents" className="text-xs text-cyan-300">运行详情</Link>} /><div className="grid gap-3 p-4 sm:grid-cols-2">{agentRuns.map(agent => <div key={agent.id} className="rounded-xl border border-white/[0.07] bg-white/[0.022] p-3.5"><div className="flex items-start justify-between"><div className="grid h-8 w-8 place-items-center rounded-lg bg-cyan-400/10 text-cyan-300"><Bot className="h-4 w-4" /></div>{agent.status === "已完成" ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : <Clock3 className="h-4 w-4 text-amber-400" />}</div><p className="mt-3 text-xs font-medium text-slate-200">{agent.name}</p><p className="mt-1 line-clamp-1 text-[10px] text-slate-600">{agent.task}</p></div>)}</div></Panel>
      <Panel><PanelHeader eyebrow="Industry intelligence" title="行业与外部情报" description="用于补充经营研判，不替代企业原始资料" /><div className="space-y-3 p-4">{[["新能源材料", "上游碳酸锂价格近 30 日回升 12.6%", "成本压力"],["高端装备", "主要出口市场新增合规审查清单", "规则变化"],["生物医药", "并购估值中枢较上季下降 8.3%", "估值观察"]].map(([industry,text,tag]) => <div key={industry} className="flex gap-3 rounded-xl border border-white/[0.06] p-3.5"><Network className="mt-0.5 h-4 w-4 shrink-0 text-blue-300" /><div><div className="flex items-center gap-2"><p className="text-xs font-medium text-slate-200">{industry}</p><span className="rounded bg-white/[0.05] px-1.5 py-0.5 text-[9px] text-slate-500">{tag}</span></div><p className="mt-1.5 text-[11px] leading-5 text-slate-500">{text}</p></div></div>)}</div></Panel>
    </div>
  </div>;
}
